/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';

export const POST_TYPES = ['STATUS', 'EVENT'];

export const NOTIFY_TYPES = ['LIKES', 'COMMENTS', 'NEW_POST'];

export const ROLES = {
  ADMINISTRATOR: 'ADMINISTRATOR',
  SUPERVISOR: 'SUPERVISOR',
  LIBRARY_MANAGER: 'LIBRARY_MANAGER',
  LIBRARY_EMPLOYEE: 'LIBRARY_EMPLOYEE',
  TEACHER: 'TEACHER',
};
